collections:
  - name: engiqueer.common
    source: http://github.com/two-first-names/engiqueer-common.git/
    type: git
  - name: engiqueer.services
    source: http://github.com/two-first-names/engiqueer-services.git/
    type: git
